# Headless dev environments: the full CLI/TUI suite and language servers.
# Toolchains stay with mise (python, node, go) and rustup (rust), installed here.
{ config, pkgs, lib, link, ... }:
{
  imports = [ ./minimal.nix ];

  home.packages = with pkgs; [
    # CLI/TUI tools
    bandwhich
    difftastic
    eza
    git-lfs
    glow
    grex
    hyperfine
    iftop
    just
    nmap
    nushell
    pandoc
    parallel
    rink
    sd
    tealdeer
    tokei
    trash-cli
    typst
    yamllint
    zellij

    # Build tools. Not cmake/meson: Nix's builds don't search /usr, so they
    # can't find apt's -dev libraries; install those (and clangd) with apt.
    bazelisk
    ccache
    mold
    ninja
    sccache

    # Cargo subcommands
    cargo-binstall # prebuilt binaries for crates not in nixpkgs
    cargo-bloat
    cargo-deny
    cargo-flamegraph
    cargo-machete
    cargo-tarpaulin
    cargo-udeps
    cargo-update # `cargo install-update -a` updates what's installed with cargo
    cargo-watch

    # Toolchain managers
    mise
    rustup
    uv

    # Nix: language server and formatter (helix and nvim use them for .nix files)
    nixd
    nixfmt

    # Language servers and formatters (see .config/helix/languages.toml)
    black
    bun
    dockerfile-language-server
    lua-language-server
    pyright
    ruff
    (lib.hiPrio rust-analyzer) # rustup ships a rust-analyzer proxy too; prefer this one
    svelte-language-server
    tailwindcss-language-server
    taplo
    tinymist
    typescript
    typescript-language-server
    vscode-langservers-extracted
    wgsl-analyzer
  ];

  # Absolute paths: hm-session-vars.sh sets these before XDG_DATA_HOME
  home.sessionVariables = with config.xdg; {
    CARGO_HOME = "${dataHome}/cargo";
    GOPATH = "${dataHome}/go";
    PNPM_HOME = "${dataHome}/pnpm";
    RUSTUP_HOME = "${dataHome}/rustup";
  };
  # Tools installed outside Nix (cargo install, pnpm add -g, go install)
  home.sessionPath = with config.xdg; [
    "${dataHome}/cargo/bin"
    "${dataHome}/pnpm"
    "${dataHome}/go/bin"
  ];

  # Neovim plugins (configured in .config/nvim/init.lua), pinned by flake.lock
  programs.neovim.plugins = with pkgs.vimPlugins; [
    (nvim-treesitter.withPlugins (p: with p; [
      bash c cpp css diff dockerfile gitcommit go html javascript json kdl lua
      make markdown markdown_inline nix nu python query regex rust starlark
      svelte toml tsx typescript typst vim vimdoc wgsl yaml
    ]))
    nvim-treesitter-context
    nvim-treesitter-textobjects
    nvim-lspconfig # default settings for the language servers installed above

    telescope-nvim
    telescope-fzf-native-nvim
    telescope-ui-select-nvim
    plenary-nvim
    nvim-web-devicons

    gitsigns-nvim
    indent-blankline-nvim
    lualine-nvim
    marks-nvim
    oil-nvim
    vim-easymotion
    which-key-nvim

    # Themes, switched by theme.sh
    everforest
    gruvbox-nvim
    nord-nvim
  ];

  # Load a project's Nix dev shell (`use flake` in .envrc) on cd. The shell
  # hooks are in .config/zsh/.zshrc, .bashrc and .config/nushell/config.nu, as
  # those files aren't generated by home-manager.
  programs.direnv = {
    enable = true;
    nix-direnv.enable = true;
  };

  xdg.configFile."mise".source = link ".config/mise";
  xdg.configFile."nushell".source = link ".config/nushell";
  xdg.configFile."zellij".source = link ".config/zellij";
}
