# Rust
[language-server.rust-analyzer.config.check]
command = "clippy"

# Python
[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
[language-server.ruff]
command = "ruff"
[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

# JS/TS
[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]
[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]
[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]
[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]
[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]
[[language]]
name = "svelte"
auto-format = true
language-servers = [ "svelteserver", "tailwindcss-ls" ]
