# Rust
[language-server.rust-analyzer.config.check]
command = "clippy"
[language-server.rust-analyzer.workspace.symbol.search]
limit = 1048576

[[language]]
name = "python"
auto-format = true
language-servers = [ "pyright", "ruff" ]
[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
config.python.analysis.typeCheckingMode = "standard"
[language-server.ruff]
command = "ruff server"
config.settings.args = ["--ignore", "E501"]

# JS/TS
[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]
[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]
[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]
[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]
[[language]]
name = "svelte"
auto-format = true
language-servers = [ "svelteserver", "tailwindcss-ls" ]
